<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="4" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Test case failed : testDisplayIntroScreensOnFirstLaunch]]>
    </line>
    <line>
      <![CDATA[<a href="http://10.9.43.129/Screenshot_testDisplayIntroScreensOnFirstLaunch_2016-10-14 12:03:17.418.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[Test case failed : testValidLoginWithGoogle]]>
    </line>
    <line>
      <![CDATA[<a href="http://10.9.43.129/Screenshot_testValidLoginWithGoogle_2016-10-14 12:04:43.666.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[Test case failed : testClassName]]>
    </line>
    <line>
      <![CDATA[<a href="http://10.9.43.129/Screenshot_testClassName_2016-10-14 12:05:57.047.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[Test case failed : testLogOut]]>
    </line>
    <line>
      <![CDATA[<a href="http://10.9.43.129/Screenshot_testLogOut_2016-10-14 12:06:18.6.jpg">Screenshot</a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="206275" started-at="2016-10-14T06:32:54Z" finished-at="2016-10-14T06:36:20Z">
    <groups>
    </groups>
    <test name="TestGmail" duration-ms="206275" started-at="2016-10-14T06:32:54Z" finished-at="2016-10-14T06:36:20Z">
      <class name="com.mobiliya.edvelop.test.TestDisplayIntroScreens">
        <test-method status="FAIL" signature="testDisplayIntroScreensOnFirstLaunch()[pri:0, instance:com.mobiliya.edvelop.test.TestDisplayIntroScreens@2038ae61]" name="testDisplayIntroScreensOnFirstLaunch" duration-ms="22937" started-at="2016-10-14T12:02:54Z" finished-at="2016-10-14T12:03:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [GET STARTEDhi] but found [GET STARTED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [GET STARTEDhi] but found [GET STARTED]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.mobiliya.edvelop.test.TestDisplayIntroScreens.testDisplayIntroScreensOnFirstLaunch(TestDisplayIntroScreens.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test case failed : testDisplayIntroScreensOnFirstLaunch]]>
            </line>
            <line>
              <![CDATA[<a href="http://10.9.43.129/Screenshot_testDisplayIntroScreensOnFirstLaunch_2016-10-14 12:03:17.418.jpg">Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- testDisplayIntroScreensOnFirstLaunch -->
      </class> <!-- com.mobiliya.edvelop.test.TestDisplayIntroScreens -->
      <class name="com.mobiliya.edvelop.test.BaseTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.mobiliya.edvelop.test.BaseTest@60c6f5b]" name="setup" is-config="true" duration-ms="46499" started-at="2016-10-14T12:02:07Z" finished-at="2016-10-14T12:02:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.mobiliya.edvelop.test.BaseTest@60c6f5b]" name="tearDown" is-config="true" duration-ms="5623" started-at="2016-10-14T12:06:20Z" finished-at="2016-10-14T12:06:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.mobiliya.edvelop.test.BaseTest -->
      <class name="com.mobiliya.edvelop.test.TestLogOut">
        <test-method status="FAIL" signature="testLogOut()[pri:0, instance:com.mobiliya.edvelop.test.TestLogOut@544fe44c]" name="testLogOut" duration-ms="19468" started-at="2016-10-14T12:05:59Z" finished-at="2016-10-14T12:06:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please sign in using email id as provided to the schoolhi] but found [Please sign in using email id as provided to the school]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please sign in using email id as provided to the schoolhi] but found [Please sign in using email id as provided to the school]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.mobiliya.edvelop.test.TestLogOut.testLogOut(TestLogOut.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test case failed : testLogOut]]>
            </line>
            <line>
              <![CDATA[<a href="http://10.9.43.129/Screenshot_testLogOut_2016-10-14 12:06:18.6.jpg">Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- testLogOut -->
      </class> <!-- com.mobiliya.edvelop.test.TestLogOut -->
      <class name="com.mobiliya.edvelop.test.TestValidLoginWithGoogle">
        <test-method status="FAIL" signature="testValidLoginWithGoogle()[pri:0, instance:com.mobiliya.edvelop.test.TestValidLoginWithGoogle@3c0f93f1]" name="testValidLoginWithGoogle" duration-ms="72623" started-at="2016-10-14T12:03:31Z" finished-at="2016-10-14T12:04:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please contact school admin in case of incorrect informationhi] but found [Please contact school admin in case of incorrect information]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please contact school admin in case of incorrect informationhi] but found [Please contact school admin in case of incorrect information]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.mobiliya.edvelop.test.TestValidLoginWithGoogle.testValidLoginWithGoogle(TestValidLoginWithGoogle.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test case failed : testValidLoginWithGoogle]]>
            </line>
            <line>
              <![CDATA[<a href="http://10.9.43.129/Screenshot_testValidLoginWithGoogle_2016-10-14 12:04:43.666.jpg">Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidLoginWithGoogle -->
      </class> <!-- com.mobiliya.edvelop.test.TestValidLoginWithGoogle -->
      <class name="com.mobiliya.edvelop.test.TestDisplayDashboard">
        <test-method status="PASS" signature="navigateToDashboard()[pri:0, instance:com.mobiliya.edvelop.test.TestDisplayDashboard@31dc339b]" name="navigateToDashboard" is-config="true" duration-ms="26673" started-at="2016-10-14T12:04:45Z" finished-at="2016-10-14T12:05:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToDashboard -->
        <test-method status="FAIL" signature="testClassName()[pri:0, instance:com.mobiliya.edvelop.test.TestDisplayDashboard@31dc339b]" name="testClassName" duration-ms="44638" started-at="2016-10-14T12:05:12Z" finished-at="2016-10-14T12:05:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [0]: Class 8 != Class 9 expected [Class 8] but found [Class 9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [0]: Class 8 != Class 9 expected [Class 8] but found [Class 9]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:670)
	at org.testng.Assert.assertEquals(Assert.java:727)
	at com.mobiliya.edvelop.test.TestDisplayDashboard.testClassName(TestDisplayDashboard.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test case failed : testClassName]]>
            </line>
            <line>
              <![CDATA[<a href="http://10.9.43.129/Screenshot_testClassName_2016-10-14 12:05:57.047.jpg">Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- testClassName -->
      </class> <!-- com.mobiliya.edvelop.test.TestDisplayDashboard -->
    </test> <!-- TestGmail -->
  </suite> <!-- Suite -->
</testng-results>
